### PR TITLE
Remove unwanted images and sounds in the project

### PR DESCRIPTION
**Pull request by DipanshKhandelwal**
issue #8 
deleted image - test.jpg
renamed image - ruless.jpg to rules.jpg.

### CODE REVIEW

**Comment by quozl** [comment]
Thanks, that's a good start, but there are other unused images.  Please;

- [ ] carefully check that each image is used,
- [ ] remove duplicate identical files, such as between `buts/` and `images/`,
- [ ] rebase your branch against the new master branch.

**Comment by DipanshKhandelwal** [comment]
ok thanks :+1:

**Comment by quozl** [comment]
Apart from code review, or `git grep`, the other way to verify if an image is used is to;

- set up code coverage analysis,
- write a code coverage test that uses all code paths,
- verify that the test has coverage,
- enable atime support on your filesystem, or use `strace -e open`,
- run the test once more,
- use atime of files or the `strace` log to verify which files have been read.

**Comment by DipanshKhandelwal** [comment]
@quozl , i have removed all the unwanted images and sounds.

**Comment by DipanshKhandelwal** [comment]
fixes #8 .

**Pull request merged**
