### PR TITLE
Adding copyright or licence

### PR DESCRIPTION
**Pull request by Aniket21mathur**
Adding copyright or licence to the source files.

Fixes https://github.com/sugarlabs/buttons-and-scissors-activity/issues/7

### CODE REVIEW

**Comment by quozl** [comment]
@iamutkarshtiwari, please review.  You are copyright owner.

**Comment by rhl-bthr** [comment]
@iamutkarshtiwari, ping

**Comment by rhl-bthr** [comment]
@iamutkarshtiwari, ping

**Comment by rhl-bthr** [comment]
Since @iamutkarshtiwari is not responding, I'm not sure what should we do

**Comment by quozl** [comment]
Other than attempting contact by mail, there's not much else we can do.  We can't act for the copyright owner without explicit consent.

**Pull request closed without merging**
