### PR TITLE
Updated LICENSE to GPLv3+

### LINKED ISSUE #4: License metadata should be GPLv3+
Currently GPLv3, should be GPLv3+ because of the "or later" phrase in the source.

### PR DESCRIPTION
**Pull request by yell0wfl4sh**
fixes #4

### CODE REVIEW

**Comment by quozl** [comment]
Oh, sorry, looks like I'm wrong now.  It should be `GPLv3+ and GPLv2+` because `setup.py` is GPLv2+.  Which happened 22 hours ago, in 92678b2f9d3a1a0e0de0495d199a5c7084498e11.

**Comment by yell0wfl4sh** [comment]
updated!

**Comment by quozl** [comment]
Your change in 8fe846c is from GPLv3 to GPLv2+, but the source has multiple licenses; GPLv3+ in `activity.py`, and GPLv2+ in `setup.py`, (a [multiple licensing scenario](https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#Multiple_Licensing_Scenarios) according to Fedora project), therefore the license metadata should be "GPLv3+ and GPLv2+".

Also see:
 * https://wiki.sugarlabs.org/go/Development_Team/Almanac/Activity_Bundles#.info_file_format

**Comment by yell0wfl4sh** [comment]
Thanks for information! :-)

**Pull request merged**
